slurm_packages_common:
  - munge
  - slurm-wlm

munge_service_name: munge

slurm_controller_service_name: slurmctld
slurm_worker_service_name: slurmd

munge_key_path: /etc/munge/munge.key
munge_user: munge
munge_group: munge
munge_key_mode: "0400"
munge_local_tmp_dir: /tmp/ai_platform_ansible_munge

slurm_cluster_name: ai_cluster
slurm_controller_host: raspberry
slurm_partition_name: debug
slurm_nodes:
  - name: jetson
    memory: 6500
    sockets: 2
    cores_per_socket: 3
    threads_per_core: 1
