FROM rust:1.95-bookworm AS builder
WORKDIR /app

COPY . .

RUN cargo build -p rag_indexer --release

FROM debian:bookworm
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/rag_indexer /usr/local/bin/rag_indexer

ENTRYPOINT ["/usr/local/bin/rag_indexer"]
