apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  nodeSelector:
    kubernetes.io/hostname: jetson
  containers:
    - name: shell
      image: alpine:latest
      command: [ "sleep", "3600" ]
      volumeMounts:
        - name: nfs-data
          mountPath: /mnt/nfs
  volumes:
    - name: nfs-data
      hostPath:
        path: /home/roman/nfs
        type: Directory
