all:
  children:
    slurm_controller:
      hosts:
        raspberry:
          ansible_host: raspberry
          ansible_user: roman
          ansible_ssh_private_key_file: /home/roman/.ssh/raspberry

    slurm_worker:
      hosts:
        jetson:
          ansible_host: jetson
          ansible_user: roman
          ansible_ssh_private_key_file: /home/roman/.ssh/jetson
