---
- name: Verify local registry
  hosts: slurm_worker
  become: false
  gather_facts: false

  pre_tasks:
    - name: Load registry vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../vars/registry.yml"

  tasks:
    - name: Check registry catalog
      ansible.builtin.uri:
        url: "http://{{ k3s_registry_name }}/v2/_catalog"
        return_content: true
      register: registry_catalog

    - name: Show registry catalog
      ansible.builtin.debug:
        msg:
          - "{{ registry_catalog.content }}"
