---
- name: Restart Slurm services after GRES config
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Load host-specific vars explicitly
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../../host_vars/{{ inventory_hostname }}.yml"

  tasks:
    - name: Restart slurmctld on controller
      ansible.builtin.service:
        name: slurmctld
        state: restarted
        enabled: true
      when: node_role == "slurm_controller"

    - name: Restart slurmd on worker
      ansible.builtin.service:
        name: slurmd
        state: restarted
        enabled: true
      when: node_role == "slurm_worker"
