apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-platform-host
  namespace: ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-platform-host
  template:
    metadata:
      labels:
        app: ai-platform-host
    spec:
      containers:
        - name: ai-platform-host
          image: 192.168.178.103:5000/ai-platform-host:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: HOST_PORT
              value: "3000"
            - name: TOOL_PROVIDER
              value: "mcp"
            - name: MCP_TOOLS_BINARY
              value: "/usr/local/bin/tools-server"
            - name: LLM_BACKEND
              value: "openai_compat"
            - name: LLM_BASE_URL
              value: "http://llama-cpp:8000"
            - name: LLM_CHAT_PATH
              value: "/api/chat"
            - name: LLM_MODEL
              value: "qwen2.5-0.5b-instruct-q4_k_m.gguf"
            - name: EMBEDDING_BACKEND
              value: "openai_compat"
            - name: EMBEDDING_BASE_URL
              value: "http://llama-cpp-embed:8001"
            - name: EMBEDDING_MODEL
              value: "all-minilm-l6-v2-q8_0.gguf"
            - name: RETRIEVAL_BACKEND
              value: "embeddings_local"
            - name: RAG_ARTIFACTS_PATH
              value: "/mnt/nfs/rag/artifacts"
            - name: LLM_LORA_BACKEND
              value: "openai_compat"
            - name: LLM_LORA_BASE_URL
              value: "http://llama-cpp-lora:8003"
            - name: LLM_LORA_MODEL
              value: "qwen-lora-gpu"

          volumeMounts:
            - name: nfs-data
              mountPath: /mnt/nfs
      volumes:
        - name: nfs-data
          hostPath:
            path: /home/roman/nfs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ai-platform-host
  namespace: ai-platform
spec:
  type: NodePort
  selector:
    app: ai-platform-host
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
